baseURL = "https://jlevesy.github.io/joinme/"
languageCode = "en-us"
title = "Organize events in a breeze"
theme = ["timer-hugo"]

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
       name    = "About"
       url     = "/#about"
       weight  = 1

    [[menu.nav]]
       name    = "Features"
       url     = "/#feature"
       weight  = 1

    [[menu.nav]]
       name    = "Get started"
       url     = "/sign-up"
       weight  = 1

# Site Params
[params]
    home = "Home"
    logo = ""
    brand = "Beevent"
    dateFormat = "6 January 2006"
    description = "Organize events easily and engage your attendees"
    author = "Bloup"
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        # Link back: Photo by Ylanite Koppens from Pexels
        bgImage = "images/proposal1.jpg"
        heading = "I want to organize"
         description = "Beevent helps you organize your events in a breeze"
        # description = "Setup, Invite, Collaborate"
        btn     = true
        btnText = "Get Started"
        btnURL  = "sign-up"
        [[params.banner.flipText]]
            title   = "A Party"
        [[params.banner.flipText]]
            title   = "A Hike"
        [[params.banner.flipText]]
            title   = "A Diner"
        [[params.banner.flipText]]
            title   = "A Trip"
        [[params.banner.flipText]]
            title   = "A Weekend"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Setup, Invite and Collaborate"
        content = "Do you want to organize a party or a weekend trip with your friends? Do you want to get their help in preparation? Beevent helps you to set up your event fast and easy.  It also a great tool for collaboration so you are not alone in preparing your event"
        image   = "images/about.png"

    [params.feature]
        # Possible icons => https://infinitered.github.io/ionicons-version-3-search/
        enable = true
        title = "This is what we bring"
        subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, possimus commodi."

        [[params.feature.item]]
            icon = "ion-ios-flask-outline"
            title = "No sign up required"
            description = "Your guests don't need any sign-up to join your event"

        [[params.feature.item]]
            icon = "ion-ios-flask-outline"
            title = "Seemless communication"
            description = "Guests receive your updates on your prefered platform. Could it be WhatsApp, Email, SMS or Facebook Messenger"

        [[params.feature.item]]
            icon = "ion-ios-flask-outline"
            title = "Task delegation"
            description = "I'll bring the pizza, you can bring the dessert! Anyone has some space in their car? Does anyone have a spare tennis racket? Easily create and assign tasks to your guests to make sure nothing gets forgotten and everyone knows how they can contribute"

        [[params.feature.item]]
            icon = "ion-ios-flask-outline"
            title = "Event templates"
            description = ""

        [[params.feature.item]]
            title = "Smart Invitations"
            icon = "ion-ios-flask-outline"
            description = "Beevent manages for you the invitation list. If someone cancels then beevent will automatically send a new inviation to the next guest on waiting list"

        [[params.feature.item]]
            icon = "ion-ios-game-controller-a"
            title = "Manage expenses"
            description = "Easilly share the event expenses with the attendees."

    # Call to Action
    [params.cta]
        enable  = true
        title   = "So, What do you think ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Get started"
        btnURL  = "sign-up"

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"
